config/routes.rb
Rails.application.routes.draw do
  resources :emails, only: [:new, :index, :create, :show]
  resources :templates, only: [:new, :create, :index]
  
  root "emails#index"
  
  get 'template_show',  to: 'emails#show_template'
  
  put 'select_template/:id',  to: 'templates#select_template', as: 'select_template'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/email.rb
class Email < ApplicationRecord
  
  validates :subject, presence: true
  validates :body, presence: true
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/models/template.rb
class Template < ApplicationRecord

  validates :name, presence: true
  validates :body, presence: true
  
  scope :selected, -> { where(selected: true) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/custom_template_controller.rb
module CustomTemplateController
  extend ActiveSupport::Concern
  
  def custom_layout
    
    name = "uploaded_template"
    
    # name = Template.last.name
    # The above will work even if you have a 'space' in the name
    
    # Generating the path
    abs_path = Rails.root.join("app/views/layouts/#{name}.html.erb")
    
    html = Template.selected.last.body.html_safe 
    
    # Writing to the file
    File.write(abs_path, html)
    
    name
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  
  before_action :set_template, only: [:index, :create, :show]
  
  def index
    @emails = Email.all
    # @template = Template.selected.last
  end

  def new
    @email = Email.new
  end

  def show
    @email = Email.find(params[:id])
    
  end

  def create
    @email = Email.new(email_params)
    
    if @email.save
      Subscriber.all.each do |subscriber|
        NewsletterMailer.email(subscriber, @email, @template).deliver_now
      end
      redirect_to emails_path, notice: "Email sent"
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def show_template
    @template = Template.last
  end

  private

    def email_params
      params.require(:email).permit(:subject, :body)
    end
    
    def set_template
      @template = Template.selected.last
    end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  
  # Custom Layout method is located in this Controller
  include CustomTemplateController
  
  before_action :previous_selected_template, only: [:create, :select_template]

  def new
    @new_template = Template.new
  end
  
  
  def create
    @new_template = Template.new(template_params)
    @new_template.selected = true
    
    if @new_template.save
      previous_template_change_to_unselect(@previous_selected) if @template.count > 1
      redirect_to root_path, notice: "Template created"
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def show
    @template = Template.last
    
  end
  
  def index
    @templates = Template.all
  end
  
  # If a Template is selected then change the necessary fields and change the layout of the template 
  def select_template
    
    @selected_template = Template.find_by_id(params[:id])
    
    if @template.empty?
      @selected_template.update(selected: true)
      custom_layout
      redirect_to root_path
    else
      @selected_template.update(selected: true)
      @previous_selected.selected = false  
      previous_template_change_to_unselect(@previous_selected)
      custom_layout
      redirect_to root_path
    end

  end
  
  private
  
  def template_params
    params.require(:template).permit(:name, :body)
  end
  
  def previous_selected_template
    @template = Template.selected
    
    unless @template.empty?
      @previous_selected = @template.last
    end
  end
  
  def previous_template_change_to_unselect(previous_selected)
    previous_selected.update(selected: false)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newsletter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/templates/index.html.erb
<div>
<div class="my-5">
	<%= link_to sanitize("&larr; Back to email sent"), root_path, class: "no-underline text-slate-600 hover:text-blue-400" %>
</div>
  
  
<div>
<table class="min-w-max w-full table-auto">
  <thead>
	  <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
		  <th class="py-3 px-6 text-left">Template name</th>
		  <th class="py-3 px-6 text-left">Select</th>
	  </tr>
  </thead>
  <tbody id="member-list"class="text-gray-600 text-sm font-light">
	  <% @templates.each do |template| %>
	  	<tr class="border-b border-gray-200 hover:bg-gray-100">
		    <td class="py-3 px-6 text-left">
		      <div class="flex items-center">
		        <%= template.name %>
		      </div>
		    </td>
			
		    <td class="py-3 px-6 text-left">
		      <div class="flex items-center">
		        <% if template.selected? %>
					Selected
				<% else %>
					<%= button_to "Select", select_template_path(template.id), method: :put, 
					class: "no-underline text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
				<% end %>
		      </div>
		    </td>
		</tr>
	  <% end %>
  </tbody>
</table>

</div>

</div>

app/views/templates/new.html.erb
<div class="prose flex-col max-w-none flex w-full">
	
  <div class="mb-5">
	 <%= link_to sanitize("&larr; Back to email sent"), root_path, class: "no-underline text-slate-600 hover:text-blue-400" %>
  </div>
	
  <h1>New Template</h1>

  <%= form_with model: @new_template do |f| %>
    <div class="mb-6">
      <%= f.label :name, class: "block mb-2 text-sm font-medium text-slate-900" %>
      <%= f.text_field :name, class: "border border-gray-300 text-slate-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
    </div>
    <div class="mb-6">
      <%= f.label :body, class: "block mb-2 text-sm font-medium text-slate-900" %>
	  <small class="text-sm italic">Please include "< % = yield % >" in the body</small>
      <%= f.text_area :body, class: "border border-gray-300 text-slate-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
    </div>
    <div><%= f.submit :send, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %></div>
  <% end %>
</div>